FROM nvcr.io/nvidia/tritonserver:25.01-trtllm-python-py3

RUN git clone https://github.com/NVIDIA/TensorRT-LLM.git
#RUN git clone https://huggingface.co/ilsp/Llama-Krikri-8B-Instruct.git

EXPOSE 8000
EXPOSE 8001
EXPOSE 8002

CMD ["/bin/bash"]